//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetalleSolicitudExamen
    {
        public int idDetalleSolicitudExamen { get; set; }
        public int idSolicitudExamen { get; set; }
        public int idExamen { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual tbExamen tbExamen { get; set; }
        public virtual tbSolicitudExamen tbSolicitudExamen { get; set; }
    }
}
