//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSolicitudExamen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSolicitudExamen()
        {
            this.tbDetalleSolicitudExamen = new HashSet<tbDetalleSolicitudExamen>();
        }
    
        public int idSolicitudExamen { get; set; }
        public int idPaciente { get; set; }
        public int idUsuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetalleSolicitudExamen> tbDetalleSolicitudExamen { get; set; }
        public virtual tbPaciente tbPaciente { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
